# Generated by Django 6.0.4 on 2026-04-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
